### ISSUE TITLE
ExportScript.ps1 - folders cannot be found

### ISSUE THREAD

**Issue by cclayton18** [Microsoft/emat#4]
We have Exchange 2010 and are preparing to go hybrid with O365/Exchange Online.  I've been testing out this tool and so far I am very encouraged.

I have noticed that during the folder enumeration step I get a lot of errors along the lines of:

The operation couldn't be performed because 'user@our.domain:\Top of Information Store' couldn't be found.
    + CategoryInfo          : NotSpecified: (:) [Get-MailboxFolderPermission], ManagementObjectNotFoundException
    + FullyQualifiedErrorId : 9C944E08,Microsoft.Exchange.Management.StoreTasks.GetMailboxFolderPermission
    + PSComputerName        : ourcashubserver.ourdomain.local

In addition to the "Top of Information Store" errors I also see ones for Versions, Purges, Deletions, Recoverable Items, and a variety of user-created folders with what I am guessing are characters the script couldn't handle...likely in the enumeration step using Get-MailboxFolderStatistics.

I'm not worried about delegated permissions on deleted item folders.  It might be nice to be able to better enumerate the user-created folders if a way can be found to handle the characters (I'm guessing slashes are particularly problematic here).

That said, it seems very reasonable to want permissions for the top level, which I think could be included by doing something like:

$utente = $folders | %{ Get-MailboxFolderPermission $($alias+":"+$_).Replace(":\Top of Information Store","") | select Identity,User,Accessrights,foldername}

**Comment by reikor0x** [comment]
Hello, check the last version of the export script that fix the issue you reported. 
It was not an error, but just something "not beautiful" to see.
