### ISSUE TITLE
struggling with large groups and blacklist.csv 

### ISSUE THREAD

**Issue by cclayton18** [Microsoft/emat#5]
After switching from our test environment to production with the tool, I'm now looking at over 6000 mailboxes (maybe 1700 of which we will likely purge before migrating to O365).  Unfortunately, I've got a persistent bundle of a different ~1700 mailboxes that all end up in the same migration group and I have had difficulty getting them broken apart.  I tried adding the mailboxes that we will eventually purge to the blacklist (by email address as exported to outputs.csv) as well as mailboxes that had a large number of relationships in the stats output file in order to break up the large group into smaller ones, but with little change in the output.  

It appears 400-500 of the mailboxes on the blacklist still appear in the outputs.csv file, almost all of them in the one big group, and I'm having a hard time coming up with something they have in common that might explain it.

I have found that blacklist.csv is apparently case-sensitive, meaning that I have to add duplicate lines like
DOMAIN\svaccount
DOMAIN\svAccount
svaccount@domain.tld
svAccount@domain.tld

Is there a limit on how many entries can go into blacklist.csv, or characters/formats that are not allowed?

Does anyone have suggestions as to how best to break apart larger groups, and how to format the blacklist file to properly exclude accounts that might be gluing everyone together?

Thank you for your help.  This is an amazingly complex analysis task.  
Chris

**Comment by reikor0x** [comment]
Hi,
there no limits for the blacklist.csv file. I have to confirm that is case-sensitive, so I manage this as a bug.
I'll update the documentation. This will be fixed in future release.
