### ISSUE TITLE
exporting send on behalf

### ISSUE THREAD

**Issue by cclayton18** [Microsoft/emat#6]
The readme states that folder permissions and send on behalf aren't exported, but clearly the script appears to be making the attempt.  I previously reported an issue with the folder permissions that was labeled a bug, so I thought I'd share what I found with send-on-behalf in case it is helpful.

In the SnB.csv file, I was seeing lines that look like this:

"domain.local/TopOU/SubOU/userCN","System.Collections.ArrayList","SNB",,

I assume the calculation is not aided by the name of the .NET class for the property extracted.  It looks like the script is attempting to produce a semicolon-delimited list inside the row of the CSV file containing the users with that permission granted.  If that is the goal, I found this line works better:

`import-csv mailboxes.csv | get-mailbox | ?{$_.GrantSendOnBehalfTo} | select Identity,@{Name='User';Expression={$_.GrantSendOnBehalfTo -join ";"}},@{Name='AccessRight';Expression={"SNB"}},ExtendedRight,FolderPath | export-csv SnB.csv -encoding "unicode" -NoTypeInformation `

The result is something along the lines of:
"domain.local/TopOU/SubOU/userCN","domain.local/TopOU/SubOU/otheruserCN;domain.local/TopOU/SubOU/anotheruserCN;domain.local/TopOU/SubOU/yetanotheruserCN","SNB",,

Of course our OUs and object names have spaces, so I don't know how well the calculation tool is making use of the data, but to my knowledge there are no semicolons in the AD data to complicate things further.  

Chris

**Comment by reikor0x** [comment]
Hi cclayton18, 
it's not really true that FP and SNB are not exported. The only limitation is for FP that require Exchange 2010+.

I tested again "my version" and it looks like that it was working fine, with multiple SNB users creating a semicolon-delimited structure.

But, looking at your suggested code, I found it very good, removing .NET reference and "more simple and compatible". So I decided to adopt in main stream version. You will find the code in the next version that will be published soon.

Thank you for the hint.

**Comment by cclayton18** [comment]
You're welcome, and thanks for the feedback.  After further testing and troubleshooting my other issues, I discovered the server I was running the tool on was only .NET 4.5.2 not 4.6.1.  The export script works fine as you indicated on my desktop PC with .NET 4.7 so I'm starting the whole process over there with the thought there may be other .NET version-dependent behavior being relied upon I hadn't noticed and worked around.

Chris
