### ISSUE TITLE
permissions_aftergroupexpansion.csv data contains commas not in quotes

### ISSUE THREAD

**Issue by cclayton18** [Microsoft/emat#7]
I'm looking at the Permissions_aftergroupexpansion.csv file and I'm seeing Identity and User values that contain commas and they aren't contained in quotes.  I am concerned that the Calculate executable is not then able to parse that data correctly when generating subsequent output files since a split on the comma character would result in more than three fields.  I'm starting to suspect that is why I have so many users getting lumped into one giant group.

It looks like there was previously an issue fixed in RC1 regarding data with commas, but it wasn't clear to me which step in the process that referred to.  The CSV files generated by ExportScript.ps1 have all relevant fields contained in quotes, so I suspect that's what was referred to.

**Comment by reikor0x** [comment]
Quotas do not influence calculation. Try new version.
